spring:  
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eicon?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: felipe95
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: 
    generate-ddl: true
    show-sql: true   
  mvc:
    hiddenmethod:
      filter:
        enabled: true  
  jackson:
    time-zone: America/Sao_Paulo